gcc:
  image: base/archlinux
  stage: build
  script:
    - pacman -Syu --needed --noconfirm meson sdl2 pkg-config fontconfig libepoxy udev libwebp openal libvorbis boost gcc
    - meson build --werror
    - ninja -C build

clang:
  image: base/archlinux
  stage: build
  script:
    - pacman -Syu --needed --noconfirm meson sdl2 pkg-config fontconfig libepoxy udev libwebp openal libvorbis boost clang-tools-extra python2-yaml
    - CC=clang CXX=clang++ meson build --werror
    - cd build
    - TERM=xterm script -qfc "ninja" /dev/null
    - sed -i s/-pipe// compile_commands.json
    - TERM=xterm script -qfc "/usr/share/clang/run-clang-tidy.py 2>/dev/null" | sed s_$PWD/__
    - '! grep -Fq "error:" typescript'

mingw:
  image: fedora:27
  stage: build
  script:
    - dnf install -y gcc-c++ meson mingw64-pkg-config mingw64-libvorbis mingw64-SDL2 mingw64-fontconfig mingw64-libjpeg-turbo mingw64-libwebp mingw64-boost mingw64-dlfcn mingw64-libepoxy mingw64-openal-soft wine-core
    - meson build --werror --cross-file mingw.ini
    - ninja -C build

android:
  image: opengisch/docker-qt-crystax
  stage: build
  script:
    - apt install -y file
    - $ANDROID_NDK_ROOT/ndk-build -j$(nproc) -Candroid/jngl
    - $ANDROID_NDK_ROOT/ndk-build -j$(nproc) -Candroid/test
