variables:
  CLICOLOR_FORCE: "1"
  TERM: xterm

gcc:
  image: fedora:28
  stage: build
  script:
    - dnf install -y fontconfig-devel freetype-devel libvorbis-devel libepoxy-devel libwebp-devel libjpeg-turbo-devel boost-python3-devel python3-devel meson SDL2-devel openal-soft-devel gcc-c++
    - meson build --werror
    - cd build
    - script -qfec "ninja" /dev/null
    - dnf install -y mesa-dri-drivers xorg-x11-drv-dummy
    - Xorg -config ../data/xorg.conf &>/dev/null &
    - sleep 1 # wait for Xorg to boot up
    - DISPLAY=:0 ./unittest

clang:
  image: fedora:28
  stage: build
  script:
    - dnf install -y fontconfig-devel freetype-devel libvorbis-devel libepoxy-devel libwebp-devel libjpeg-turbo-devel boost-python3-devel python3-devel meson SDL2-devel openal-soft-devel clang
    - CC=clang CXX=clang++ script -qfec "meson build --werror" /dev/null
    - cd build
    - script -qfec "ninja" /dev/null
    - dnf install -y clang-tools-extra python3-PyYAML
    - sed -i s/-pipe// compile_commands.json
    - script -qfec "python3 /usr/share/clang/run-clang-tidy.py 2>/dev/null" | sed s_$PWD/__
    - '! grep -Fq "error:" typescript'

mingw:
  image: fedora:27
  stage: build
  script:
    - dnf install -y gcc-c++ meson mingw64-pkg-config mingw64-libvorbis mingw64-SDL2 mingw64-fontconfig mingw64-libjpeg-turbo mingw64-libwebp mingw64-boost mingw64-dlfcn mingw64-libepoxy mingw64-openal-soft wine-core
    - meson build --werror --cross-file mingw.ini
    - script -qfec "ninja -C build" /dev/null
    - rm -rf build
    - meson build --werror --cross-file mingw.ini --buildtype release --unity on
    - ninja -C build

android:
  image: jhasse/android-ndk:r19b
  stage: build
  script:
    - make -C android
