image: base/archlinux

before_script:
  - pacman -Syu --needed --noconfirm meson sdl2 pkg-config fontconfig glew libwebp openal libvorbis boost

gcc:
  stage: build
  script:
    - pacman -S --needed --noconfirm gcc
    - meson build
    - ninja -C build

clang:
  stage: build
  script:
    - pacman -S --needed --noconfirm clang-tools-extra python2
    - CC=clang CXX=clang++ meson build
    - cd build
    - TERM=xterm script -qfc "ninja" /dev/null
    - sed -i s/-pipe// compile_commands.json
    - TERM=xterm script -qfc "/usr/share/clang/run-clang-tidy.py 2>/dev/null" | sed s_$PWD/__
    - '! grep -Fq "error:" typescript'

variables:
  GIT_SUBMODULE_STRATEGY: recursive
