language: cpp
os:
- linux
- windows
dist: bionic
compiler:
  - clang
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd doc && cmake . && make && docker run -v$PWD/..:/w -it fedora:31 /bin/sh -c "dnf install -y graphviz doxygen && cd /w/doc && doxygen"; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then cmake -Bbuild -H. -AWin32 && cmake --build build; fi
deploy:
  local-dir: doc/html
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
    condition: $TRAVIS_OS_NAME = linux
