language: cpp
os:
- linux
- osx
compiler:
  - gcc
dist: trusty
sudo: false
addons:
  apt:
    packages:
      - libfreetype6-dev
      - libvorbis-dev
      - libopenal-dev
      - libsdl2-dev
      - libglew-dev
      - libboost-dev
      - libwebp-dev
      - libboost-python-dev
install:
- |
  [ $TRAVIS_OS_NAME = linux ] || brew update
- |
  [ $TRAVIS_OS_NAME = linux ] || brew upgrade jpeg
- |
  [ $TRAVIS_OS_NAME = linux ] || brew install sdl2 freetype libvorbis glew jpeg webp scons
script:
  - scons verbose=1 debug=1
  - scons verbose=1
  - |
    [ $TRAVIS_OS_NAME = osx ] || scons verbose=1 python=1 debug=1
  - |
    [ $TRAVIS_OS_NAME = osx ] || scons verbose=1 python=1
