name: Android

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: [ubuntu-latest]
    container:
      image: registry.gitlab.com/jhasse/android-ndk-docker:23-0-7599858
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: make -C android
