name: Documentation
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: sudo apt install doxygen graphviz
    - name: Doxygen
      run: |
        cd doc
        cmake .
        make
        doxygen
